[package]
name = "brix_cli"
version = "0.1.0"
authors = ["Miapolis <41233357+Miapolis@users.noreply.github.com>"]
edition = "2018"

[dependencies]
brix_errors = { path = "../../crates/brix_errors" }
dialoguer = "0.8.0"

[dependencies.clap]
version = "2.33.3"
default-features = false
features = ["suggestions", "color"]
