[package]
name = "brix_cli"
version = "0.1.0"
authors = ["Miapolis <41233357+Miapolis@users.noreply.github.com>"]
edition = "2018"

[dependencies]
brix_errors = { path = "../../crates/brix_errors" }
colour = "^0"
