on: [push]
name: build
jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt, clippy
    - run: cargo fmt --all -- --check
    - run: cargo check --all
    - run: cargo clippy --all
    - run: cargo build --all
    - run: cargo test --all
