on: [push]
name: build
jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt, clippy
    - name: cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all
    - name: cargo fmt check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all
    - name: cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all
    - name: cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all
    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all
